[package]
name = "ggmusic"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
lofty = "0.20"
id3 = "1.13"
anyhow = "1"
env_logger = "0.11"
rodio = "0.18"
